### ISSUE TITLE
Add support for a template to create the person page

### ISSUE THREAD

**Issue by BrommD** [reorx/obsidian-people-link#4]
**Is your feature request related to a problem? Please describe.**
When creating new person/contact, the file is a 0 byte file. I would like to have an option to define a free chosable template file here, so I can fill up it later with additional information. 

**Describe the solution you'd like**
another option field to define a template for new contacts file creation.

**Describe alternatives you've considered**
replacing the new 0-byte file with a suitable template file.

**Additional context**

**Comment by chrisweis** [comment]
Can’t the Templater extension already provide this if you configure a [folder template](https://silentvoid13.github.io/Templater/settings.html#folder-templates) ?

**Comment by BrommD** [comment]
Hi, good catch! Yes, this works like required. Request can be closed. thx
